---

# unfortunately, gather_facts/setup doesn't gather a list of enabled repositories,
# thus we can't just depend on a fact
- name: check maildrop copr
  shell:
      cmd: |
          dnf -C repolist enabled -v  | grep '^Repo-id' | awk '$3 == "copr:copr.fedorainfracloud.org:gsauthof:epel" {print "enabled"}'
      warn: no
  check_mode: no
  changed_when: false
  register: maildrop_copr
  when:
      - ansible_distribution in ('CentOS', 'RedHat', 'Red Hat Enterprise Linux')
  tags: [pkg, maildrop]

# we need maildrop >= 3, as of 2020, CentOS 7 EPEL doesn't have it
- name: enable maildrop copr
  command:
      cmd: dnf -y copr enable gsauthof/epel
      #creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:gsauthof:epel.repo
      warn: no
  when:
      - ansible_distribution in ('CentOS', 'RedHat', 'Red Hat Enterprise Linux')
      - maildrop_copr.stdout == ''
  tags: [pkg, maildrop]

- name: install maildrop
  package:
      name:
          - maildrop
      state: latest
  tags: [pkg, maildrop]

- name: install extra packages
  package:
      name:
          - selinux-policy-devel
          - gonzofilter
      state: latest
  notify: restorecon
  tags: [pkg, selinux, maildrop]

- name: set maildrop shell to bash
  copy:
      src: maildroprc
      dest: /etc/maildroprc
      owner: root
      group: root
      mode: '0644'
  tags: [maildroprc, maildrop]

# Alternative way to enable a Copr repo - doesn't abstract away implementation
# details how Copr .repo files are built.
#
#- name: enable copr
#  yum_repository:
#      name: "copr:copr.fedorainfracloud.org:{{ item[0] }}:{{ item[1] }}"
#      file: "_copr:copr.fedorainfracloud.org:{{ item[0] }}:{{ item[1] }}"
#      description: "{{ item[2] }}"
#      baseurl: "{{ copr_url }}/results/{{ item[0] }}/{{ item[1] }}/epel-{{ ansible_distribution_major_version }}-$basearch/"
#      gpgkey: "{{ copr_url }}/results/{{ item[0] }}/{{ item[1] }}/pubkey.gpg"
#      gpgcheck: yes
#      enabled: yes
#      skip_if_unavailable: yes
#  when:
#      - ansible_distribution in ('CentOS', 'RedHat', 'Red Hat Enterprise Linux')
#  vars:
#      copr_url: https://copr-be.cloud.fedoraproject.org
#      #copr_url: https://download.copr.fedorainfracloud.org
#  loop:
#      - [gsauthof, epel, "Copr repo for epel owned by gsauthof"]
#  tags: pkg

- name: get maildrop version
  shell: maildrop -v  | head -n 1 | cut -d ' ' -f2
  register: maildrop_version
  check_mode: no
  changed_when: false
  tags: [pkg, maildrop]

- name: check maildrop version
  assert:
      that:
          - maildrop_version.stdout is version('3', '>=')
      msg: 'We need Maildrop >= 3 for the :H expression option'
  ignore_errors: "{{ ansible_check_mode }}"
  tags: [pkg, maildrop]


- name: copy selinux policy modules
  copy:
      src: selinux/
      dest: /root/selinux/
  register: sepol
  tags: [selinux, maildrop]

- name: remove state files if policy changed
  file:
      state: absent
      path: /root/selinux.loaded
  when: sepol.changed
  tags: [selinux, maildrop]


- name: load selinux policies
  shell:
      cmd: |
          set -eux
          for i in maildrop gonzofilter; do
              cd /root/selinux/$i
              make -f /usr/share/selinux/devel/Makefile $i.pp
              /usr/sbin/semodule -i $i.pp
          done
          /sbin/restorecon -F -R -v /usr/bin/maildrop
          /sbin/restorecon -F -R -v /usr/bin/gonzofilter
          touch /root/selinux.loaded
      creates: /root/selinux.loaded
  notify: restorecon
  tags: [selinux, maildrop]



- name: create maildirectories
  file:
      path: "/home/{{ mda_user + '/' + item[0] + '/' + item[1] }}"
      state: directory
      owner: "{{ mda_user }}"
      group: "{{ mda_user }}"
      mode: '0700'
      setype: _default
      seuser: _default
  # the _default isn't sufficient when creating all directories from scratch
  # i.e. executing the playbook multiple times isn't sufficient
  notify: restorecon
  tags: [conf, maildrop, maildir]
  vars:
      - maildirs:
          - md/copy
          - md/ham
          - md/spam
          - md/spamfilter
          - md/spool
          - "{{ inbox_dir }}"
          - "{{ inbox_dir }}/.Spam"
  loop: "{{ (maildirs + local_maildirs) | product(['cur', 'new', 'tmp']) | list }}"

- name: copy mailfilter
  template:
      src: mailfilter.j2
      dest: "/home/{{ mda_user }}/.mailfilter"
      owner: "{{ mda_user }}"
      group: "{{ mda_user }}"
      mode: '0600'
      setype: _default
      seuser: _default
  notify: restorecon
  tags: [conf, maildrop, mailfilter]

- name: cron job - remove old mail
  cron:
        name: "clean_mail_{{ item.1.name }}"
        minute: "{{ item.0 * 5 % 60 }}"
        hour: "19"
        job: "find ~/md/{{ item.1.name }} -maxdepth 2 -type f -mtime +{{ item.1.days }} -print0 | xargs -0 -r rm"
        user: "{{ mda_user }}"
  with_indexed_items:
      - { name: copy,       days:  60 }
      - { name: spamfilter, days: 720 }
      - { name: spam,       days: 720 }
      - "{{ extra_md_clean }}"
  tags: [cron, maildrop]

- name: create train spam script
  copy:
      remote_src: yes
      src: /root/utility/train-spam.sh
      dest: /usr/local/bin/train-spam.sh
      owner: root
      group: root
      mode: '0755'
  tags: [cron, localbin, maildrop]

- name: cron job - train spam
  cron:
        name: train_spam
        minute: "0"
        hour: "18"
        # calls gonzofilter which eats all mail under ~/maildir/.Spam/ which
        # were moved there by an IMAP client
        # cf. https://github.com/gsauthof/utility
        job: PATH=/usr/local/bin:$PATH /usr/local/bin/train-spam.sh
        user: "{{ mda_user }}"
  tags: [cron, maildrop]

- name: cron job - check dnsbl
  cron:
        name: check-dnsbl
        minute: "30"
        hour: "7"
        # cf. https://github.com/gsauthof/utility
        job: "check-dnsbl {{ ns_flag }} {{ other_host }}"
        user: "{{ mda_user }}"
        cron_file: check-dnsbl
  vars:
    - ns_flag: "{% if extra_ns %}--ns {{ extra_ns }}{% endif %}"
    - other_host: "{{ hostvars[(hostvars.keys() | list)[((hostvars | length) + (hostvars.keys() | list).index(inventory_hostname) - 1) % (hostvars | length)]].mx_name }}"
  tags: [cron, maildrop]

- name: cron job - check certs
  cron:
        name: check-cert
        minute: "35"
        hour: "7"
        # cf. https://github.com/gsauthof/utility
        job: "check-cert {{ other_host }}_{25_smtp,443,993}"
        user: "{{ mda_user }}"
        cron_file: check-cert
  vars:
    - other_host: "{{ hostvars[(hostvars.keys() | list)[((hostvars | length) + (hostvars.keys() | list).index(inventory_hostname) - 1) % (hostvars | length)]].mx_name }}"
  tags: [cron, maildrop]


